#!/bin/sh

PKGSBRANCH=v1.5.0

renice -n 19 $$

rm -Rf build
git clone --depth 1 -b $PKGSBRANCH https://github.com/siderolabs/pkgs build

mkdir build/kernel/prepare/patches
cp patch_2_of_5.patch build/kernel/prepare/patches

cp add_patch_2_of_5.patch build

cd build

git apply add_patch_2_of_5.patch

sed -i 's/kconfig-hardened-check/kernel-hardening-checker/g' kernel/build/pkg.yaml
sed -i 's/kconfig-hardened-check/kernel-hardening-checker/g' kernel/prepare/pkg.yaml

make -j$(nproc) USERNAME=rsmitty PUSH=true PLATFORM=linux/arm64 REGISTRY=127.0.0.1:5000 kernel 

cd ..
