#!/bin/sh


TALOSRELEASE=v1.5.5

set -e

renice -n 19 $$

rm -Rf build
git clone --depth 1 -b $TALOSRELEASE https://github.com/siderolabs/talos build

cp -v *.patch build

cd build

git apply custom_uboot_and_kernel.patch
#git apply remove_boost_add_stable_corefreq.patch

make -j$(nproc) clean

#make uki-certs
make -j$(nproc) kernel initramfs PLATFORM=linux/arm64
make -j$(nproc) installer IMAGE_REGISTRY=127.0.0.1:5000 PLATFORM=linux/arm64 PUSH=true
make -j$(nproc) imager IMAGE_REGISTRY=127.0.0.1:5000 PLATFORM=linux/arm64 PUSH=true
make -j$(nproc) iso IMAGE_REGISTRY=127.0.0.1:5000 PLATFORM=linux/arm64 PUSH=true 
make -j$(nproc) sbc-rpi_generic IMAGE_REGISTRY=127.0.0.1:5000 PLATFORM=linux/arm64 PUSH=true

echo 'clean /dev/sda with:'
echo 
echo 'sudo wipefs -a /dev/sda ; sync'
echo
echo
echo 'write image with:'
echo
echo 'time xz -d < _out/metal-rpi_generic-arm64.raw.xz | sudo dd of=/dev/sda bs=1M status=progress conv=fsync ; sync'
echo

cd ..
